# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '\.bat'
      - id: trailing-whitespace
  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.24.2
    hooks:
      - id: latexindent
        args: ["--overwriteIfDifferent", "-r",  "--silent", "-l=.latexindent.yaml"]
        types: [file]
        files: '\.(tex|sty|cls|bib|cfg|def|clo)$'
