# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '\.bat'
      - id: trailing-whitespace
  - repo: local
    hooks:
    -   id: l3build-tag
        name: ensure to run l3build tag
        description: run l3build tag to mark \changes
        entry: l3build
        pass_filenames: false
        args: ["tag"]
        language: system
        always_run: true
