# Based on the template repositories published with https://github.com/TeXhackse/tugboat-tug2024-cicd
name: Test document using l3build

on:
  push:
  pull_request:

# Cancel running builds on push on the same branch or pull request
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  doc:
    runs-on: ubuntu-22.04
    name: Documentation and Demo files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages
          cache_version: 0
      - name: Run l3build
        run: l3build doc -q -H
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "*.pdf"
          retention-days: 21
